import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Nav from '../components/Nav';
import Number from '../components/Number';
import React from 'react';
import Line from '../components/Line';
import String from '../components/String';
import List from '../components/List';

export default function Home() {
  return (
    <div className="bg-finanflixBlack min-h-screen pb-32">
      <Head>
        <title>Clase 1 Rating Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="w-8/12 lg:w-6/12 m-auto">
        <Number />
        <Line />
        <String />
        <Line />
        <List />
      </div>
    </div>
  );
}
