import Head from 'next/head';
import Nav from '../components/Nav';
import Number from '../components/Number';
import React from 'react';
import Line from '../components/Line';
import String from '../components/String';
import List from '../components/List';
import { useAccount } from 'wagmi';

export default function Home() {
  const { address } = useAccount();
  return (
    <div className="bg-finanflixBlack min-h-screen pb-32">
      <Head>
        <title>Clase 1 Rating Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="w-8/12 lg:w-6/12 m-auto">
        {address === undefined ? (
          <p className="text-finanflixWhite font-extrabold my-[30px] text-[42px]">
            Por favor, conecte su wallet
          </p>
        ) : (
          <>
            <Number />
            <Line />
            <String />
            <Line />
            <List />
          </>
        )}
      </div>
    </div>
  );
}
