import Head from 'next/head';
import Nav from '../components/Nav';
import React, { useEffect, useState } from 'react';
import { useAccount } from 'wagmi';

export default function Home() {
  const { address, isConnected } = useAccount();

  const [connected, setConnected] = useState(false);
  const [wallet, setWallet] = useState(undefined);

  useEffect(() => {
    setConnected(isConnected);
  }, [isConnected]);

  useEffect(() => {
    setWallet(address);
  }, [address]);

  return (
    <div className="bg-finanflixPurple min-h-screen pb-32 font-poppins selection:bg-finanflixOrange">
      <Head>
        <title>Clase 1 Rating Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="w-11/12 md:w-8/12 lg:w-6/12 m-auto">
        {connected === false && wallet === undefined ? (
          <p className="text-center text-finanflixWhite font-extrabold my-[30px] text-[42px]">
            Por favor, conecte su wallet
          </p>
        ) : (
          <>
            <p>hola</p>
          </>
        )}
      </div>
    </div>
  );
}
